name: reel_t
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.5
  preload_page_view: 0.1.6
  video_player: 2.6.1
  cached_network_image: 3.2.3
  firebase_core: 2.8.0
  cloud_firestore: 4.4.5
  shared_preferences: 2.0.20
  provider: 6.0.5
  firebase_auth: 4.3.0
  internet_connection_checker: 1.0.0+1
  firebase_storage: 11.0.16
  firebase_database: 10.0.16
  crypto: 3.0.2
  visibility_detector: 0.4.0+2
  readmore: 2.2.0
  intl: 0.17.0
  hive: 2.2.3
  flutter_staggered_grid_view: 0.6.2
  path_provider: 2.0.14
  hive_generator: 2.0.0
  build_runner: 2.3.3
  connectivity_plus: 3.0.3
  comment_tree: 0.3.0
  uuid: 3.0.7
  shimmer: 2.0.0
  google_fonts: 4.0.3
  otp_text_field: 1.1.3
  mailer: 6.0.0
  modal_bottom_sheet: 3.0.0-pre
  photo_manager: 2.6.0
  like_button: 2.0.5
  cloud_functions: 4.0.13
  google_sign_in: 6.1.0
  platform_local_notifications: 0.0.3
  animated_text_kit: 4.2.2
  flutter_svg: 2.0.5
  image_picker: 0.8.7+1
  permission_handler: 10.2.0
  email_validator: 2.1.17
  flutter_pw_validator: 1.5.0
  video_thumbnail: 0.5.3
  video_compress: 3.1.2
  camerawesome: 1.4.0
  gallery_saver: 2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - lib/shared_product/assets/
    - lib/shared_product/assets/icon/

  fonts:
    - family: TikTokIcons
      fonts:
        - asset: lib/shared_product/assets/fonts/TikTokIcons.ttf
