isStoreLocal: True
arguments:
  - id: String
  - userIds: List<String>
  - messages: Message
  - secondUser: UserProfile
  - latestMessage: String
  - isMute: bool
  - isDeleted: bool
  - createAt: int
  - updateAt: int