arguments:
  - id: String
  - fullName: String
  - email: String
  - displayName: String
  - avatar: String
  - numFollower: String
  - numFollowing: String
  - isOnline: bool
  - isActive: bool
  - isDeleted: bool