arguments:
  - id: String
  - fullName: String
  - email: String
  - displayName: String
  - avatar: String
  - numFollower: int
  - numFollowing: int
  - isOnline: bool
  - isActive: bool
  - isDeleted: bool