isStoreLocal: True
arguments:
  - id: String
  - fullName: String
  - email: String
  - userName: String
  - bio: String
  - birthday: String
  - avatar: String
  - numFollower: int
  - numFollowing: int
  - numLikes: int
  - signUpType: int
  - isOnline: bool
  - isActive: bool
  - isDeleted: bool
  - createAt: int
enums:
  - sign_up_type:
    - google
    - email
    - both