arguments:
  - videoUrl: String
  - songName: String
  - creatorId: String
  - title: String
  - publicMode: int
  - commentsNum: int
  - likesNum: int
  - viewsNum: int
  - isDeleted: bool
  - like: Like
  - followCreator: Follow
  - comment: Comment
  - creator: UserProfile
enums:
  - public_mode:
      - public
      - private
