arguments:
  - id: String
  - videoUrl: String
  - songName: String
  - creatorId: String
  - title: String
  - publicMode: int
  - commentsNum: int
  - likesNum: int
  - viewsNum: int
  - isDeleted: bool
enums:
  - public_mode:
      - public
      - private
