// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT4k5PbxMdcOIL-uNgezCj7F-a8NK6YE0',
    appId: '1:505266246761:web:072eb22d970b66737efef8',
    messagingSenderId: '505266246761',
    projectId: 'reel-t-6b2ba',
    authDomain: 'reel-t-6b2ba.firebaseapp.com',
    databaseURL: "https://reel-t-6b2ba-default-rtdb.firebaseio.com/",
    storageBucket: 'reel-t-6b2ba.appspot.com',
    measurementId: 'G-KJR7QCE7EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmZ2jhIsyjYITBUobi6LybaXi2l5recVI',
    appId: '1:505266246761:android:ba4eff3fc60058997efef8',
    messagingSenderId: '505266246761',
    databaseURL: "https://reel-t-6b2ba-default-rtdb.firebaseio.com/",
    projectId: 'reel-t-6b2ba',
    storageBucket: 'reel-t-6b2ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAILt5LWcSKB1dIbeH8zJjE6tT7WDRJyyc',
    appId: '1:505266246761:ios:05141d0a7e07601c7efef8',
    messagingSenderId: '505266246761',
    projectId: 'reel-t-6b2ba',
    databaseURL: "https://reel-t-6b2ba-default-rtdb.firebaseio.com/",
    storageBucket: 'reel-t-6b2ba.appspot.com',
    iosClientId:
        '505266246761-cjc5m4jtln9b0dd0011nq9d5h3pp1j10.apps.googleusercontent.com',
    iosBundleId: 'com.example.reelt',
  );
}
