// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARUejJmVIiT51REutZXejIbN9kOXwppS4',
    appId: '1:363289285640:web:30e2e0a4253e06e5422dbd',
    messagingSenderId: '363289285640',
    projectId: 'reel-t',
    authDomain: 'reel-t.firebaseapp.com',
    storageBucket: 'reel-t.appspot.com',
    measurementId: 'G-1EF8HKK8NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdKruN3_bBTo-ZkIzIw4W6YWQAOAGggVg',
    appId: '1:363289285640:android:01f99ea0aee01e0f422dbd',
    messagingSenderId: '363289285640',
    projectId: 'reel-t',
    storageBucket: 'reel-t.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Jrkzqmn7F7sy00GCC_H2_5HbexP7ats',
    appId: '1:363289285640:ios:2df70494dbce4a50422dbd',
    messagingSenderId: '363289285640',
    projectId: 'reel-t',
    storageBucket: 'reel-t.appspot.com',
    iosClientId: '363289285640-i4packi8kouqpita4jg3bj33af8igdkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.reelt',
  );
}
